### ISSUE TITLE
Pipeline run has failed at the last task health-check

### ISSUE THREAD

**Issue by indirakalagara** [ibm-garage-ref-storefront/devops-pipelines#10]
Problem:

Pipeline run has failed at the last task health-check.

  Pointed the pipeline to the below release and remove the gitops task to continue further. However it failed at the last task. 
  url: https://github.com/ibm-garage-ref-storefront/pipelines-server/releases/download/17.0/default-kabanero-pipelines.tar.gz

**Comment by oiricaud** [comment]
We have resolved this issue in our latest release.
