### ISSUE TITLE
Please make the pipeline more generic

### ISSUE THREAD

**Issue by indirakalagara** [ibm-garage-ref-storefront/devops-pipelines#11]
Problem:

Currently the pipeline naming convention is using storefront as. it is inline with sample application.  However the tasks are common across the applications, request you to create the pipeline name similar to the  cp4app pipeline naming conventions.

**Comment by oiricaud** [comment]
@csantanapr What do you think?

**Comment by csantanapr** [comment]
@indirakalagara can you provide an example of the name your proposing. 

We have to be careful trying to name the pipeline with every task function it contains it would be too long. Long Mamés for resources create problems in Kubernetes in addition that random suffixes are added

**Comment by indirakalagara** [comment]
I think the name could be in similar lines of what we have existing cp4app  pipelines.
