### ISSUE TITLE
Roadmap of the pipeline

### ISSUE THREAD

**Issue by indirakalagara** [ibm-garage-ref-storefront/devops-pipelines#12]
Team,

Please let us know what is the roadmap of this pipeline ?  Is this going to be part of ICP4App kabanero pipelines ? It would be great as it has additional tasks like sonarqube integration, code scan, health check etc as part of it.  By adding it to default list of pipelines, it will help add more value to the Accelerators for teams as developer doesn't need to focus on updating / creating custom pipelines.

**Comment by oiricaud** [comment]
Great question,

Thanks for reaching out. You can view more information about our pipelines here https://cloudnativereference.dev/related-repositories/pipelines

As far as the road map, we have introduced 5 pipelines that come in this repository which are 
<img width="820" alt="Screen Shot 2020-07-21 at 9 29 35 AM" src="https://user-images.githubusercontent.com/11867058/88067516-b2662d00-cb34-11ea-9477-150cbc97dfb2.png">
