### ISSUE TITLE
Pipeline is failed on the gitops task

### ISSUE THREAD

**Issue by indirakalagara** [ibm-garage-ref-storefront/devops-pipelines#9]
Problem:

I have pointed the pipeline with the release
  url: https://github.com/ibm-garage-ref-storefront/pipelines-server/releases/download/17.0/default-kabanero-pipelines.tar.gz

and it failed to run as it points to the gitops-task not found

tkn pr ls -n kabanero
NAME                                 STARTED        DURATION    STATUS                   
storefront-springboot-pl-run-rkjd9   1 minute ago   0 seconds   Failed(CouldntGetTask)

tkn pr logs storefront-springboot-pl-run-rkjd9 -n kabanero
Pipeline kabanero/storefront-springboot-pl can't be Run; it contains Tasks that don't exist: Couldn't retrieve Task "custom-java-spring-boot2-gitops-task": task.tekton.dev "custom-java-spring-boot2-gitops-task" not found

**Comment by oiricaud** [comment]
We have resolved this in our latest release :)
